[package]
name = "gsv"
version = "0.1.0"
authors = ["thve <t.vermersch@betclicgroup.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
yaml-rust = "0.4"
exitcode = "1.1.2"